function  [trainedClassifier] =  callmyclassifier2(Classifiername,predictors,response)
%UNTITLED7 Summary of this function goes here
%   Detailed explanation goes here

%[trainedClassifier, validationAccuracy] = myClassifier(trainingdataSet);
%classifiers {'Fine knn', 'Weighted knn', 'LDA', 'SVM' , 'cubic SVM' };

switch Classifiername
    case 'Fine knn'
        disp('Fine Knn Classifier: ');
        trainedClassifier = fitcknn(...
            predictors, ...
            response, ...
            'Distance', 'Euclidean', ...
            'Exponent', [], ...
            'NumNeighbors', 10, ...
            'DistanceWeight', 'SquaredInverse', ...
            'Standardize', true, ...
            'ClassNames', [0; 1]);
        
    case 'Weighted knn'
        disp('Weighted Knn Classifier: ');
        trainedClassifier  = fitcknn(...
            predictors, ...
            response, ...
            'Distance', 'Euclidean', ...
            'Exponent', [], ...
            'NumNeighbors', 10, ...
            'DistanceWeight', 'SquaredInverse', ...
            'Standardize', true, ...
            'ClassNames', [0; 1]);
    case 'LDA'
        disp('LDA Classifier: ');
        trainedClassifier = fitcdiscr(...
            predictors, ...
            response, ...
            'DiscrimType', 'linear', ...
            'Gamma', 0, ...
            'FillCoeffs', 'off', ...
            'ClassNames', [0; 1]);
    case 'SVM'
        disp('SVM Classifier: ');
        trainedClassifier= fitcsvm(...
            predictors, ...
            response, ...
            'KernelFunction', 'gaussian', ...
            'PolynomialOrder', [], ...
            'KernelScale', 24, ...
            'BoxConstraint', 1, ...
            'Standardize', true, ...
            'ClassNames', [0; 1]);
    case 'cubic SVM'
        disp('Cubic SVM Classifier: ');
        trainedClassifier= fitcsvm(...
            predictors, ...
            response, ...
            'KernelFunction', 'polynomial', ...
            'PolynomialOrder', 3, ...
            'KernelScale', 'auto', ...
            'BoxConstraint', 1, ...
            'Standardize', true, ...
            'ClassNames', [0; 1]);
end


end

