function [criterion] = my_funFineKnn(xT,yT,xt,yt)

trainingResponse = yT;
trainingPredictors = xT;

classificationKNN = fitcknn(...
    trainingPredictors, ...
    trainingResponse, ...
    'Distance', 'Euclidean', ...
    'Exponent', [], ...
    'NumNeighbors', 1, ...
    'DistanceWeight', 'Equal', ...
    'Standardize', true, ...
    'ClassNames', [0; 1]);
    
criterion = getclasserror(yt,predict(classificationKNN,xt));

end






