function [criterion] = my_funcubicSVM(xT,yT,xt,yt)

trainingResponse = yT;
trainingPredictors = xT;

classificationSVM = fitcsvm(...
    trainingPredictors, ...
    trainingResponse, ...
    'KernelFunction', 'polynomial', ...
    'PolynomialOrder', 3, ...
    'KernelScale', 'auto', ...
    'BoxConstraint', 1, ...
    'Standardize', true, ...
    'ClassNames', [0; 1]);
    
criterion = getclasserror(yt,predict(classificationSVM,xt));

end